services:
  fastapi:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: BlackSpeaker13
      POSTGRES_PASSWORD: fastapi_db
      POSTGRES_DB: w4chiu
    ports:
      - "6543:6543"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    
volumes:
  postgres_data: